# Site settings
title: "Modesto Scripting Language Meetup"
description: "Modesto Scripting Language Meetup"
baseurl: ""
url: "http://mslm.github.io"

# Build settings
permalink: /:categories/:year/:month/:title/
markdown: kramdown