# Site settings
title: "Modesto Scripting Language Meetup"
description: "Modesto Scripting Language Meetup"
baseurl: "http://mslm.github.io"
url: "http://mslm.github.io"

# Build settings
permalink: pretty